### ISSUE TITLE
SSO support

### ISSUE THREAD

**Issue by tomd8451** [nicohaenggi/SafariBooks-Downloader#18]
I have a SSO account setup with Safari, so I can't specify a password. When logging into Safari, after typing in my email I am redirected to my SSO screen to login with my credentials. Ultimately would love some form of being able to specify that I use SSO and have SafariBooks-Downloader pop up a browser window for me to log in and capture the cookie returned for subsequent requests.

**Comment by frayos** [comment]
+1

**Comment by nicohaenggi** [comment]
Duplicate of #4
