### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by sekhar989** [nicohaenggi/SafariBooks-Downloader#24]
I'm trying to download a book with the help of the guidelines mentioned in the documentation. Below is the code which I'm running:
`safaribooks-downloader -b 97777777777777 -u username@gmail.com -p password -o ~/book.epub`

I'm getting the below error:
`[safari-downloader] starting application...`
`[safari-downloader] StatusCodeError: 400 - {"error":"invalid_grant","error_description":"Invalid credentials given."}`

As per the error description, it's not the case, as I'm giving the correct credentials.
Note: The Safari-Books Online account is a Personal Trial Account.

**Comment by nicohaenggi** [comment]
@sekhar989 I am not sure about this issue and have not experienced this so far. I just tried it with my personal trial account and had no issues whatsoever. Anyone else experiencing this problem?

**Comment by junkh3ap** [comment]
Just an FYI that I'm seeing the same behavior.

**Comment by sekhar989** [comment]
@nicohaenggi  Pleased to inform that it works absolutely fine... The invalid credentials error was gone once I changed my password to a simple format.
The character '$' was present in my password which I removed and tried again. Works like a charm!!
Thank you so much for such an amazing product !! :) :) Cheers !!

**Comment by milan496** [comment]
Hello I have the same error - in my case I have corporate account on safari - it means when sign in into safari online I only write username/email and redirected to corporate sign in page - can safari downloader to solve it somehow?
