### ISSUE TITLE
After few downloads, its getting stuck

### ISSUE THREAD

**Issue by LingarajBagali** [nicohaenggi/SafariBooks-Downloader#44]
I am running in a `for` loop from inside a python script, it is stuck after few downloads.
Is there a limit on the usage ?

**Comment by LingarajBagali** [comment]
Ran the command for just one id but it has got stuck at this point.
no file is created in the folder as well.

![image](https://user-images.githubusercontent.com/39855043/50739781-d1c78e80-120a-11e9-846e-1745957b7850.png)

**Comment by hypr2771** [comment]
Hi again mate,
Would you mind using the `--debug` switch to get some information about where it got stuck please?
Thanks !

**Comment by LingarajBagali** [comment]
> Hi again mate,
> Would you mind using the `--debug` switch to get some information about where it got stuck please?
> Thanks !

I will do as you asked me to and then will provide the logs here, Thank you. 👍

**Comment by LingarajBagali** [comment]
I have installed [this one](https://github.com/hypr2771/SafariBooks-Downloader.git).
And, version says
![image](https://user-images.githubusercontent.com/39855043/50784149-e40cff80-12d2-11e9-8173-e318fd9b30aa.png)
But, i am not able to use debug option, it says the option is invalid.
![image](https://user-images.githubusercontent.com/39855043/50784197-0141ce00-12d3-11e9-94dd-1bd6dfb4d8b1.png)
![image](https://user-images.githubusercontent.com/39855043/50784229-161e6180-12d3-11e9-84b2-c1138284c23a.png)

![image](https://user-images.githubusercontent.com/39855043/50784213-0d2d9000-12d3-11e9-9c87-3abd2a692032.png)
![image](https://user-images.githubusercontent.com/39855043/50784236-1a4a7f00-12d3-11e9-8ba5-072bd5972539.png)

Please help!

**Comment by bmitchinson** [comment]
https://gist.github.com/bmitchinson/a0fded7aef97106131613ea7b39a8b60

Here's what I used to download multiple books automated on Windows. Takes a text file with URLs for each book, and scrapes their title from the page to use as the epub file name 👍

**Comment by LingarajBagali** [comment]
> https://gist.github.com/bmitchinson/a0fded7aef97106131613ea7b39a8b60
> 
> Here's what I used to download multiple books automated on Windows with Python 3.6. Reads from a text file with URLs for each book, and scrapes their title from the page to use as the epub file name 👍

Thank you so much for letting me know of this. But, one problem, I dont seem to call like this

**Comment by LingarajBagali** [comment]
> https://gist.github.com/bmitchinson/a0fded7aef97106131613ea7b39a8b60
> 
> Here's what I used to download multiple books automated on Windows with Python 3.6. Reads from a text file with URLs for each book, and scrapes their title from the page to use as the epub file name 👍

Thank you for letting me know of that script but, i am facing issues in getting `safaribooks-downloader` command setup globally, please help.
