### ISSUE TITLE
StatusCodeError - 302

### ISSUE THREAD

**Issue by LingarajBagali** [nicohaenggi/SafariBooks-Downloader#46]
![image](https://user-images.githubusercontent.com/39855043/51222880-8ed18d80-1965-11e9-853c-226ba02ebca9.png)

I am getting this error.

**Comment by nicohaenggi** [comment]
can you please provide the book id you are experiencing this error with?

**Comment by LingarajBagali** [comment]
Like all of them but now, its fine.
I will keep an eye, if i see that again then would post back. for now closing the issue.
