### ISSUE TITLE
Error 302

### ISSUE THREAD

**Issue by chelo034** [nicohaenggi/SafariBooks-Downloader#53]
{ request:
   { debugId: 1,
     uri: 'https://www.safaribooksonline.com/oauth2/access_token/',
     method: 'POST',
     headers:
      { host: 'www.safaribooksonline.com',
        'content-type': 'application/x-www-form-urlencoded',
        accept: 'application/json',
        'content-length': 164 },
     body:
      
{ response:
   { debugId: 1,
     headers:
      { 'content-type': 'text/html',
        location: 'https://www.oreilly.com/oauth2/access_token/',
        'content-length': '0',
        'accept-ranges': 'bytes',
        date: 'Mon, 01 Apr 2019 20:44:10 GMT',
        via: '1.1 varnish',
        connection: 'close',
        'x-client-ip': '200.87.95.220',
        'x-served-by': 'cache-scl19420-SCL',
        'x-cache': 'MISS',
        'x-cache-hits': '0',
        'x-timer': 'S1554151450.906593,VS0,VE191' },
     statusCode: 302,
     body: undefined } }
[safari-downloader] StatusCodeError: 302 - undefined

**Comment by PrismaPhonic** [comment]
I'm also getting 302's right now

**Comment by carlevison** [comment]
First time trying this and i've ran into the same issue.

@hypr2771 have you any insight into this?

**Comment by wajeehulhassanvii** [comment]
tried after sometimes, same issue

**Comment by rongfengliang** [comment]
@chelo034  may be change lib/safari/index.js like below  will works 

```diff
const Safari = function Safari(debug) {

  // ## prepare base settings
  - this.baseUrl = "https://www.safaribooksonline.com";
 + this.baseUrl = "https://learning.oreilly.com";
```

**Comment by assertcarlos** [comment]
Thank you I’ll try that when I get back.

**Comment by rongfengliang** [comment]
@assertcarlos  i do some test it  works  

download binary file [safaribooks-downloader-macos](https://raw.githubusercontent.com/rongfengliang/My-SafariBooks-Downloader/master/safaribooks-downloader-macos) for  test  && parms  the some as this project

**Comment by assertcarlos** [comment]
Changing the url solved the problem :) thanks again.

**Comment by chelo034** [comment]
problem solved, thank you.
