### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by vnsam** [nicohaenggi/SafariBooks-Downloader#6]
[safari-downloader] starting application...
[safari-downloader] the user "ccuty_07" was successfully authorized...
[safari-downloader] downloaded meta files...
[safari-downloader] downloaded table of content files...
[safari-downloader] downloaded chapter files...
[safari-downloader] downloaded stylesheet files...
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, open '.'

**Comment by vnsam** [comment]
npm is expecting a file with extension.

**Comment by nicohaenggi** [comment]
@vnsam Can you elaborate on this a bit further? So I might be able to change the docs accordingly.

**Comment by attilavago** [comment]
Same issue here.

`[safari-downloader] downloaded meta files...
[safari-downloader] downloaded table of content files...
[safari-downloader] downloaded chapter files...
[safari-downloader] downloaded stylesheet files...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, open '/Users/myUsername/Documents/development/SafariBooks-Downloader'`

**Comment by dhakchianandan** [comment]
@vnsam How did you fix this?

**Comment by suchcodemuchwow** [comment]
@ghost @nicohaenggi @vnsam you should enter path like this:
`/Users/myUsername/Documents/development/SafariBooks-Downloader/bookname.epub`
