### ISSUE TITLE
Rendering error.

### ISSUE THREAD

**Issue by kkwan-tc** [nicohaenggi/SafariBooks-Downloader#64]
This might be a particular book issue, but wondering if there's anything that can be done.
I've tried downloading this 
https://learning.oreilly.com/library/view/bad-data-handbook/9781449324957/index.html

When I open the book this error shows up in some pages. (the book is incomplete).
![image](https://user-images.githubusercontent.com/40668524/59691999-0b38f880-91b2-11e9-84eb-f95fff1bc41e.png)

Any inputs appreciated.

Thanks!

**Comment by Brando27615** [comment]
Kenny, try converting the ePub from the tool into a MOBI first. Then
convert from a MOBI into an ePub again.

I used Calibre and it works fine now.

**Comment by kkwan-tc** [comment]
@Brando27615 thank you that works! :)

**Comment by Brando27615** [comment]
Cool! I had issues initially also as I put all of my stuff into Google Books.
