### ISSUE TITLE
[Bug] Getting Invalid Credentials Given Error

### ISSUE THREAD

**Issue by kjain9878** [nicohaenggi/SafariBooks-Downloader#8]
I am trying with correct credentials but its giving me `Invalid Credentials Given` Error.
```
StatusCodeError: 400 - {"error":"invalid_grant","error_description":"Invalid credentials given."}
```

**Comment by nicohaenggi** [comment]
@kjain9878 Could you please elaborate on this a bit further? As it seems, other people are also experiencing the same issues. It would be great if you could tell us what you did to fix the issue.

**Comment by kjain9878** [comment]
Well, the simple solution would be to use email id instead of username. It worked for me. But sometimes it won't.
